# Generated by Django 5.2.5 on 2025-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at'], 'verbose_name': 'Search History', 'verbose_name_plural': 'Search Histories'},
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='City_name_58811a_idx',
            old_name='weather_app_name_9af065_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='City_latitud_2b0a2d_idx',
            old_name='weather_app_latitud_f1c73d_idx',
        ),
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='SearchHisto_user_id_25fdbe_idx',
            old_name='weather_app_user_id_71b92f_idx',
        ),
        migrations.RenameIndex(
            model_name='userfavoritelocation',
            new_name='UserFavorit_user_id_6c63b2_idx',
            old_name='weather_app_user_id_b8fdce_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherdata',
            new_name='WeatherData_city_id_f672bd_idx',
            old_name='weather_app_city_id_789e59_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherforecast',
            new_name='WeatherFore_city_id_79a9c7_idx',
            old_name='weather_app_city_id_352448_idx',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritelocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country_code', 'latitude', 'longitude'), name='unique_city'),
        ),
        migrations.AddConstraint(
            model_name='userfavoritelocation',
            constraint=models.UniqueConstraint(fields=('user', 'city'), name='unique_user_favorite_location'),
        ),
        migrations.AddConstraint(
            model_name='weatherdata',
            constraint=models.UniqueConstraint(fields=('city', 'observed_at'), name='unique_weather_data'),
        ),
        migrations.AddConstraint(
            model_name='weatherforecast',
            constraint=models.UniqueConstraint(fields=('city', 'forecast_time'), name='unique_weather_forecast'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='searchhistory',
            table='SearchHistory',
        ),
        migrations.AlterModelTable(
            name='userfavoritelocation',
            table='UserFavoriteLocation',
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='WeatherData',
        ),
        migrations.AlterModelTable(
            name='weatherforecast',
            table='WeatherForecast',
        ),
    ]
